### ISSUE TITLE
Show uwdata: Open Source Blogging Platform w/ GitHub Pages & Native Support For Jupyter and Altair

### ISSUE THREAD

**Issue by hamelsmu** [uwdata/visualization-curriculum#10]
@jheer I really loved these tutorials on Altair, as they demystified Altair for me.  

I'm working with [Jeremy Howard](https://github.com/jph00) (@jph00) on [fastpages](https://github.com/fastai/fastpages)

The reason we created this is we wanted a blogging system that was easy to use but also open source, and where people could own their data. Plus, we wanted to support cool features like interactive charts & graphs in Altair!   A summary of features is below, which can also be viewed on [the README](https://github.com/fastai/fastpages):

![image](https://user-images.githubusercontent.com/1483922/74594715-49f7aa80-4fee-11ea-8c63-24f4787ec459.png)

Sharing this incase it is interesting for your students, especially to share their cool visualization projects!   Thank you  🙇

**Comment by domoritz** [comment]
Fastpages looks really neat. I'd love to hear if you have ideas for how the notebooks in this repo could be presented with fastpages.

**Comment by hamelsmu** [comment]
@domoritz yes, take a look at https://covid19dashboards.com/ that's a bunch of Altair presented with fastpages
