### ISSUE TITLE
Width 'step' does not work

### ISSUE THREAD

**Issue by Juan-132** [uwdata/visualization-curriculum#11]
Great tutorial, very clear and helpful. Thanks!

https://github.com/uwdata/visualization-curriculum/blob/master/altair_marks_encoding.ipynb

This code is used a number of times, but does not seem to be valid.
```python
.properties(
    width={"step": 50} # adjust the step parameter
)
```
A numerical value does work: e.g.  `width=100`
I could not find from the documentation how to apply the `step`

**Comment by jheer** [comment]
Hi! Which version of Altair are you using? The step syntax was introduced with 4.0. If you are using an earlier version of Altair (3.x), you can use earlier versions of the notebooks, as described in the README: https://github.com/uwdata/visualization-curriculum#local-installation

**Comment by Juan-132** [comment]
Thanks. I was indeed still using v3.2 (which is the latest offered on conda main).
Now installed v4.01 via conda-forge; and it works perfectly
