### ISSUE TITLE
Build a Jupyter book

### ISSUE THREAD

**Issue by domoritz** [uwdata/visualization-curriculum#13]
Similar to https://github.com/altair-viz/altair-tutorial. It would make it easier to read the documents and even download them as PDF.

**Comment by joelostblom** [comment]
One note regarding making it easier to read the notebooks online is to add `alt.renderers.enable('mimetype')` on top of each notebook. This will insert a png blob as a fallback when the Vegaspec can't be rendered, so it means that at least static images will show up on when viewing the notebook on GitHub.

I can add this if you want, but ultimately I agree that building a jupyter book like https://altair-viz.github.io/altair-tutorial/README.html would be the best solution, I can try to help with this also in a few weeks unless you prefer to do it yourselves. It has been on my agenda to learn more about Jupyter Book anyways.

**Comment by domoritz** [comment]
I am currently spending my free cycles on https://github.com/cmudig/draco2, which also uses Jupyter book to render the docs. I really like it and it would be awesome if you could make a book for this repo.
