### ISSUE TITLE
Permission to remix the material from this repo into our univeristy course

### ISSUE THREAD

**Issue by joelostblom** [uwdata/visualization-curriculum#20]
Hello! We would like to remix much of the material from this repo into one of our university courses (with accreditation of course) and I just wanted to double check if this is OK. The remixing will mostly entail reordering to fit with our curriculum and extending the material where we see fit. I saw that the license is BSD-3 for the repo, but just wanted to double check before going ahead with this.

**Comment by domoritz** [comment]
You are absolutely allowed to remix the materials as long as you link back to the originals. In fact, it would be great to hear about your experience using the materials. Also, if you find any improvements that make sense for these materials, please send us a pull request.

**Comment by joelostblom** [comment]
@domoritz Our course got postponed so I will report back on the experience next year instead. On a related point, I wonder if we can use the cartographic chapter as part of [a section on geoviz that I want to add to the Altair docs](https://github.com/altair-viz/altair/issues/2580). We will hopefully add some additional subsections that could be contributed back here if they make sense to include in the UWdata course.

**Comment by jheer** [comment]
@joelostblom I’m the author of the cartographic visualization notebook. Please feel free to use it to improve the Altair docs, ideally with attribution or a link to the original. Thanks!

**Comment by joelostblom** [comment]
Thank you @jheer!
