### ISSUE TITLE
Broken link for timeunits

### ISSUE THREAD

**Issue by ltirrell** [uwdata/visualization-curriculum#24]
The "[complete list of time units](https://altair-viz.github.io/user_guide/transform.html#timeunit-transform)" link in the "Time Units" section of `altair_data_transformation.ipynb` is broken.

Should probably be replaced with:
https://altair-viz.github.io/user_guide/transform/timeunit.html#user-guide-timeunit-transform

**Comment by domoritz** [comment]
Can you send a pull request to fix it?
