### ISSUE TITLE
Typo: "it's use"

### ISSUE THREAD

**Issue by jdonland** [uwdata/visualization-curriculum#30]
The note callout box beneath the document's introductory paragraph uses the contraction form "it's" (i.e. "it is") where the possessive form "its" is correct.

**Comment by domoritz** [comment]
You mean here: https://github.com/uwdata/visualization-curriculum/blob/f7a5b2c5c4154b33d266c2073ab5a15c5f084832/altair_scales_axes_legends.ipynb#L2582?

**Comment by domoritz** [comment]
Fix for observable: https://observablehq.com/compare/4df9f19ca1d2afda...8358ca8dde228ba2

**Comment by jdonland** [comment]
Here 
![image](https://github.com/user-attachments/assets/8d3c572f-0e3d-4d43-aa05-4945ed1ec1e3)

**Comment by domoritz** [comment]
Where is this? Looks like a quarto fork?

**Comment by jdonland** [comment]
Indeed, but I assumed the Quarto project was in this repo. Apparently not!

**Comment by domoritz** [comment]
There was a typo in this repo though and I fixed it.

**Comment by jdonland** [comment]
I've been [Gettiered](https://en.wikipedia.org/wiki/Gettier_problem).
