### ISSUE TITLE
[Altair-Intro] `alt.renderers.enable('jupyterlab')` is not a part of renderer discussion

### ISSUE THREAD

**Issue by kanitw** [uwdata/visualization-curriculum#4]
In https://github.com/uwdata/visualization-curriculum/blob/master/altair_introduction.ipynb, there is a section about  renderers on the top of the page:

![image](https://user-images.githubusercontent.com/111269/57003358-fb6e4200-6b7a-11e9-922a-d6f19d6042f1.png)

Yet, `alt.renderers.enable('jupyterlab')` call is actually happening when we call  chart the first time.  

![image](https://user-images.githubusercontent.com/111269/57003356-f4473400-6b7a-11e9-99b2-3852d226a227.png)

**Comment by domoritz** [comment]
Jupyterlab does not need to be enabled explicitly. Altair works out of the box there. You only need it to reset the renderer.

**Comment by kanitw** [comment]
> Jupyterlab does not need to be enabled explicitly. Altair works out of the box there.

Well, if it's not required, remove it (before closing this issue)?  

The existence of the code there isn't related to the text surrounding it (and conflicts with the text in the section on the top that the code is not required).

**Comment by jheer** [comment]
Sorry, I misunderstood your issue. Someone else added that line -- which I didn't know was there -- so I was confused. I'll remove it now and republish the notebook. Thanks!
