### ISSUE TITLE
Solution to the handson task in altair_interaction.ipynb?

### ISSUE THREAD

**Issue by jingwb222** [uwdata/visualization-curriculum#7]
This Altair tutorial is easily the most comprehensive one I have ever seen, and such a great primer for beginners like me. However, there is a tricky task in one of those notebooks which I'm running into

> Putting into action what we've learned so far: can you modify the movie scatter plot above (the one with the dynamic query over years) to include a rule mark that shows the average IMDB (or Rotten Tomatoes) rating for the data contained within the year interval selection?

Here's my approach to the problem:
```python
brush = alt.selection_interval(
    encodings=['x'] # limit selection to x-axis (year) values
)

# dynamic query histogram
years = alt.Chart(movies).mark_bar().add_selection(
    brush
).encode(
    alt.X('year(Release_Date):T', title='Films by Release Year'),
    alt.Y('count():Q', title=None)
).properties(
    width=650,
    height=50
)

# scatter plot, modify opacity based on selection
ratings = alt.Chart(movies).mark_circle().encode(
    x='Rotten_Tomatoes_Rating:Q',
    y='IMDB_Rating:Q',
    tooltip='Title:N',
    opacity=alt.condition(brush, alt.value(0.75), alt.value(0.05))
).properties(
    width=650,
    height=400
)

ratings_mean = alt.Chart(movies).mark_rule(color='#aaa').encode(
    y='mean(IMDB_Rating):Q'
).transform_filter(
    brush
)

alt.vconcat(years, ratings+ratings_mean).properties(spacing=5)
```

which throws me `Javascript Error: Undefined data set name: "concat_1_layer_1_main"`.

Since the error does not have any traceback, I have no idea how to troubleshoot and get stuck. Could you please help me with that?

**Comment by domoritz** [comment]
I just copied your code and it actually works for me. See https://colab.research.google.com/drive/1rU_DydQ5UvN2-nea7XvBND5I1FbJKaHG?usp=sharing.
